
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class frmPedido extends javax.swing.JFrame {
    String ing[]= {"Palta", "Tomate","Chucrut","Salsa Americana"};
    int precio [] = {500,400,300,200};
    Connection conex = null;
    Statement stmt=null;
    
    /**
     * Creates new form frmPedido
     */
    public frmPedido() {
        conectar();
        initComponents();
        llenarCombo();
    }
    
    public void conectar(){
        String url="jdbc:mysql://localhost:3306/completon";
        String user="root";
        String pass="";
        
        try{
            conex=DriverManager.getConnection(url, user, pass);
            JOptionPane.showMessageDialog(null,"conectados"); 
        }
        catch(Exception sqlE){
            JOptionPane.showMessageDialog(null,"sin conectar" + sqlE);
        }
    }
    
    public void desconectar(){
        conex = null;
        stmt = null;
    }
    
    public void llenarCombo(){
        String select ="";
        select="SELECT descripFP FROM formapago";
        try{
            stmt=conex.createStatement();
            ResultSet lista=stmt.executeQuery(select);
            while(lista.next()){
                cmbPago.addItem(lista.getString("descripFP"));
            }
          
        }
        catch(SQLException sqlE){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTamano = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();
        chkPalta = new javax.swing.JCheckBox();
        chkTomate = new javax.swing.JCheckBox();
        chkChucrut = new javax.swing.JCheckBox();
        chkSalsa = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        lblTamano = new javax.swing.JLabel();
        rdbNormal = new javax.swing.JRadioButton();
        rdbGrande = new javax.swing.JRadioButton();
        lblPago = new javax.swing.JLabel();
        cmbPago = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSucursal = new javax.swing.JList<>();
        cmdPedido = new javax.swing.JButton();
        txtPalta = new javax.swing.JTextField();
        txtTomate = new javax.swing.JTextField();
        txtChucrut = new javax.swing.JTextField();
        txtSalsa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pswP = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cmdVentana = new javax.swing.JButton();
        cmdVentana2 = new javax.swing.JButton();
        txtDireccion1 = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        cmdSalir.setMnemonic('s');
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSalir);
        cmdSalir.setBounds(632, 601, 90, 23);

        lblTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lblTitulo.setText("Completon");
        jPanel2.add(lblTitulo);
        lblTitulo.setBounds(330, 59, 117, 32);

        lblNombre.setText("Nombre Completo");
        jPanel2.add(lblNombre);
        lblNombre.setBounds(70, 220, 110, 14);

        lblTelefono.setText("Telefono");
        jPanel2.add(lblTelefono);
        lblTelefono.setBounds(70, 260, 90, 14);

        lblDireccion.setText("Direccion");
        jPanel2.add(lblDireccion);
        lblDireccion.setBounds(70, 300, 80, 14);

        lblIngredientes.setText("Ingredientes");
        jPanel2.add(lblIngredientes);
        lblIngredientes.setBounds(180, 350, 90, 14);

        chkPalta.setText("Palta");
        chkPalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPaltaActionPerformed(evt);
            }
        });
        jPanel2.add(chkPalta);
        chkPalta.setBounds(180, 370, 90, 23);

        chkTomate.setText("Tomate");
        jPanel2.add(chkTomate);
        chkTomate.setBounds(180, 410, 90, 23);

        chkChucrut.setText("Chucrut");
        chkChucrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChucrutActionPerformed(evt);
            }
        });
        jPanel2.add(chkChucrut);
        chkChucrut.setBounds(180, 450, 90, 20);

        chkSalsa.setText("Salsa Americana");
        chkSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSalsaActionPerformed(evt);
            }
        });
        jPanel2.add(chkSalsa);
        chkSalsa.setBounds(180, 490, 130, 23);

        txtNombre.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel2.add(txtNombre);
        txtNombre.setBounds(177, 137, 200, 30);

        txtTelefono.setPreferredSize(new java.awt.Dimension(200, 30));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(180, 260, 200, 30);

        txtNombreC.setPreferredSize(new java.awt.Dimension(200, 30));
        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreC);
        txtNombreC.setBounds(180, 220, 200, 30);

        lblTamano.setText("Tamaño");
        jPanel2.add(lblTamano);
        lblTamano.setBounds(400, 290, 50, 14);

        bgTamano.add(rdbNormal);
        rdbNormal.setText("Normal");
        rdbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNormalActionPerformed(evt);
            }
        });
        jPanel2.add(rdbNormal);
        rdbNormal.setBounds(459, 287, 90, 23);

        bgTamano.add(rdbGrande);
        rdbGrande.setText("Grande");
        jPanel2.add(rdbGrande);
        rdbGrande.setBounds(459, 313, 90, 23);

        lblPago.setText("Pago");
        jPanel2.add(lblPago);
        lblPago.setBounds(420, 140, 40, 14);

        jPanel2.add(cmbPago);
        cmbPago.setBounds(480, 140, 100, 20);

        lstSucursal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Viña del Mar", "Con Con", "Valparaiso" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstSucursal);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(483, 193, 160, 72);

        cmdPedido.setText("Pedido");
        cmdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdPedido);
        cmdPedido.setBounds(74, 601, 170, 23);
        jPanel2.add(txtPalta);
        txtPalta.setBounds(330, 370, 40, 30);
        jPanel2.add(txtTomate);
        txtTomate.setBounds(330, 410, 40, 30);
        jPanel2.add(txtChucrut);
        txtChucrut.setBounds(330, 450, 40, 30);
        jPanel2.add(txtSalsa);
        txtSalsa.setBounds(330, 490, 40, 30);

        jLabel1.setText("Cantidad");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(330, 350, 43, 14);

        pswP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswPActionPerformed(evt);
            }
        });
        jPanel2.add(pswP);
        pswP.setBounds(515, 366, 111, 20);

        jLabel2.setText("Pass");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(483, 369, 22, 14);

        cmdVentana.setText("Ventana");
        cmdVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVentanaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdVentana);
        cmdVentana.setBounds(518, 406, 100, 23);

        cmdVentana2.setText("Ventana2");
        cmdVentana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVentana2ActionPerformed(evt);
            }
        });
        jPanel2.add(cmdVentana2);
        cmdVentana2.setBounds(350, 600, 120, 23);

        txtDireccion1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccion1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtDireccion1);
        txtDireccion1.setBounds(180, 300, 200, 30);

        txtApellido.setPreferredSize(new java.awt.Dimension(200, 30));
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido);
        txtApellido.setBounds(180, 180, 200, 30);

        lblNombre1.setText("Nombre");
        jPanel2.add(lblNombre1);
        lblNombre1.setBounds(70, 140, 80, 14);

        lblNombre2.setText("Apellido");
        jPanel2.add(lblNombre2);
        lblNombre2.setBounds(70, 180, 90, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void chkPaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPaltaActionPerformed

    private void chkChucrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChucrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChucrutActionPerformed

    private void chkSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSalsaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCActionPerformed

    private void rdbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNormalActionPerformed

    private void cmdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPedidoActionPerformed
        String pago ="",
        nombre="",
        direccion = "",
        telefono="",
        sucursal = "",
        ingredientes ="",
        tamano = "",
        insert = "";
        
        int monto = 0;
        
        nombre = txtNombre.getText();
        direccion = txtNombreC.getText();
        telefono = txtTelefono.getText();
        sucursal = lstSucursal.getSelectedValue();
        pago = String.valueOf(cmbPago.getSelectedItem());
        
        if (rdbNormal.isSelected()){
            tamano = rdbNormal.getText();
        }
        else{
            if (rdbGrande.isSelected()){
                tamano = rdbGrande.getText();
            }
        }
        
        monto = calculo();
        try{
            stmt = conex.createStatement();
            insert="INSERT INTO pedido (ingreB,fpB,totalB)VALUES('"+ingredientes+"','"+pago+"',"+monto+")"; 
            stmt.executeUpdate(insert);
            JOptionPane.showMessageDialog(null,"datos guardados");
        }
        catch (SQLException errrI){
            JOptionPane.showMessageDialog(null,"no guardados" + errrI); 
        }
        JOptionPane.showMessageDialog(null,
                "Nombre " + nombre +"\nDireccion " + direccion +"\nTelefono " + telefono + "\nMétodo Pago " + pago + "\nIngredientes " +ingredientes + "\nTamaño " + tamano +"\nSucursal "+ sucursal  +"\nMonto " + monto,
                "Pedido" + "\nMonto: " + monto,  1);
    }//GEN-LAST:event_cmdPedidoActionPerformed

    private void cmdVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVentanaActionPerformed
        String pass = String.valueOf(pswP.getPassword());
        
        frmVentana ventana = new frmVentana(pass);
        ventana.setVisible(true);
    }//GEN-LAST:event_cmdVentanaActionPerformed

    private void pswPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswPActionPerformed

    private void cmdVentana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVentana2ActionPerformed
        String pass = "";
        pass=String.valueOf(pswP.getPassword());
        jfForm2 v1 = new jfForm2(pass);
        v1.setVisible(true);
        
    }//GEN-LAST:event_cmdVentana2ActionPerformed

    private void txtDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion1ActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        String nom;
        nom="";
        nom=txtNombre.getText()+ " " +txtApellido.getText();
        txtNombreC.setText(nom);
    }//GEN-LAST:event_txtApellidoFocusLost
    
    public int getPrecio(String ingrediente, int cantidad){
        int valor = 0;
        int i = 0;
        boolean encontro = false;
        while (i<4 && encontro == false){
            if (ing[i].equals(ingrediente)){
                encontro = true;
                valor = precio[i] * cantidad;
            }
            i++;
        }
        
        return valor;
    };
    
    public int calculo(){
        
        int monto = 0;
        
        if (chkPalta.isSelected()){
            String ingrediente = chkPalta.getText();
            int cantidad = Integer.parseInt(txtPalta.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        if (chkTomate.isSelected()){
            String ingrediente = chkTomate.getText();
            int cantidad = Integer.parseInt(txtTomate.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        if (chkChucrut.isSelected()){
            String ingrediente = chkChucrut.getText();
            int cantidad = Integer.parseInt(txtChucrut.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        if (chkSalsa.isSelected()){
            String ingrediente = chkSalsa.getText();
            int cantidad = Integer.parseInt(txtSalsa.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        return monto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTamano;
    private javax.swing.JCheckBox chkChucrut;
    private javax.swing.JCheckBox chkPalta;
    private javax.swing.JCheckBox chkSalsa;
    private javax.swing.JCheckBox chkTomate;
    private javax.swing.JComboBox<String> cmbPago;
    private javax.swing.JButton cmdPedido;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdVentana;
    private javax.swing.JButton cmdVentana2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstSucursal;
    private javax.swing.JPasswordField pswP;
    private javax.swing.JRadioButton rdbGrande;
    private javax.swing.JRadioButton rdbNormal;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtChucrut;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtPalta;
    private javax.swing.JTextField txtSalsa;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTomate;
    // End of variables declaration//GEN-END:variables
}
